//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public int Itemid { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> FPrice { get; set; }
        public Nullable<int> FQuantity { get; set; }
    }
}
