//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblOrderHistories = new HashSet<tblOrderHistory>();
        }
    
        public int Uid { get; set; }
        public string UName { get; set; }
        public string UPassword { get; set; }
    
        public virtual ICollection<tblOrderHistory> tblOrderHistories { get; set; }
    }
}
